sonar.projectKey=cw-pbb-worker
sonar.projectName=CW Portfolio Builder Backend Worker
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.exclusions=node_modules/**,dist/**,logs/**,scripts/**,deploy.ps1,**/*.spec.ts,**/*.test.ts,.vscode/**,**/*.md,**/*.json,**/*.yml,**/*.yaml,**/*.html,**/*.css,**/*.scss,**/*.less,**/*.sass,**/*.styl,**/*.tsbuildinfo,**/*.d.ts,**/*.map,**/*.lock,**/tsconfig.json,**/eslint*.*,**/prettier*.*,**/webpack*.*,**/rollup*.*,**/gulp*.*,**/grunt*.*,**/jest*.*,**/*/*.babel*.*,**/ava*.*,**/nyc*.*,**/tslint*.*,**/stylelint*.*,**/commitlint*.*,**/husky*.*,templates/**